Renamed/relocated tagged release.

diff --git a/src/unix/stella.SlackBuild b/src/unix/stella.SlackBuild
--- a/src/unix/stella.SlackBuild
+++ b/src/unix/stella.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# $Id: stella.SlackBuild,v 1.14 2009-05-01 11:25:07 stephena Exp $
+# $Id: stella.SlackBuild,v 1.3 2005-10-24 14:22:15 stephena Exp $
 
 # stella.SlackBuild for Stella 2.x, B. Watson, 2005
 
@@ -13,7 +13,7 @@ die() {
 	exit 1
 }
 
-VERSION=2.8.1
+VERSION=2.0.1
 ARCH=${ARCH-i486}
 BUILD=1
 
@@ -26,7 +26,7 @@ mkdir -p $PKG
 
 cd $TMP
 tar xvfz $CWD/stella-$VERSION-src.tar.gz
-cd stella-$VERSION || die "You must run this script in the same directory as the stella-$VERSION-src.tar.gz archive"
+cd stella-$VERSION || die "extraction failed"
 
 if [ "$BUILD_GL" = "" ]; then
 	NOGL="--disable-gl"
